apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: apache-bluegreen

spec:
  replicas: 4

  selector:
    matchLabels:
      app: apache-bluegreen

  strategy:
    blueGreen:
      activeService: apache-active-service
      previewService: apache-preview-service
      autoPromotionEnabled: false

  template:
    metadata:
      labels:
        app: apache-bluegreen

    spec:
      containers:
      - name: apache

        image: httpd:2.4.62

        ports:
        - containerPort: 80

        command: ["/bin/sh", "-c"]

        args:
        - echo "<h1>GREEN VERSION - LIVE APP</h1>" > /usr/local/apache2/htdocs/index.html && httpd-foreground
